package tg.mt;

import tg.io.Hex;

/**
 * The durable form of a stored auth_key: its bytes and how it was seeded.
 *
 * <h3>Why the version lives inside the value</h3>
 * The provenance has to survive exactly as long as the key it describes, and it
 * has to be wrong in the same direction if anything goes wrong. Put in a second
 * record - a settings string beside the key - a half-completed write leaves a
 * key marked with a version it was not generated by, which is worse than no
 * version at all. Inside the one value it is written, read back and verified by
 * the same operation that stores the key, and there is no state in which one
 * exists without the other.
 *
 * <h3>The two forms</h3>
 * <pre>
 *   &lt;512 hex&gt;         no version recorded - a key stored before this field
 *                        existed, read as SEEDING_UNKNOWN_LEGACY
 *   p&lt;n&gt;:&lt;512 hex&gt;    seeding version n
 * </pre>
 *
 * A key whose provenance is {@link AuthKey#SEEDING_UNKNOWN_LEGACY} is written
 * back in the bare form, never as {@code p0:}. Two reasons, both about not
 * touching what carries the session for the sake of tidiness: the record is
 * already exactly as informative as the bare form, and a handset downgraded to
 * an older build keeps reading it. What is stored still says what is true.
 *
 * <h3>What is never rewritten</h3>
 * A version larger than {@link AuthKey#SEEDING_CURRENT} comes from a build that
 * knows something this one does not. It round trips untouched: decoding accepts
 * it, {@link AuthKey} carries it, and encoding writes the same number back. It
 * is never clamped to current and never reported as legacy.
 *
 * <h3>No key material in an answer</h3>
 * A damaged value is described by its shape - a length, a position - exactly as
 * {@code RmsAuthKeyStore} describes one. The value itself is the session, and
 * these strings reach diagnostics and the crash log, both of which are uploaded
 * on request.
 */
public final class AuthKeyRecord
{
    /** Marks a value that carries a seeding version. */
    private static final char VERSION_TAG = 'p';
    private static final char VERSION_END = ':';

    /** A stored key is exactly this many hex characters. */
    private static final int HEX_LENGTH = AuthKey.KEY_SIZE * 2;

    /**
     * Bound on the digits accepted for a version.
     *
     * Not a limit on how many seeding versions there can ever be - it is what
     * stops a corrupt record from turning into a long parse before it is
     * rejected, and it keeps {@link #seedingOf} allocation-free.
     */
    private static final int MAX_VERSION_DIGITS = 4;

    private AuthKeyRecord() { }

    /** The value to store for {@code key}. */
    public static String encode(AuthKey key)
    {
        String hex = Hex.encode(key.bytes());
        if (key.provenance() == AuthKey.SEEDING_UNKNOWN_LEGACY)
        {
            return hex;
        }
        return VERSION_TAG + Integer.toString(key.provenance())
               + VERSION_END + hex;
    }

    /**
     * Read a stored value back.
     *
     * @param value what storage held, or null
     * @return {@code FOUND} with the key and its provenance, {@code NOT_FOUND}
     *         for a null value, or {@code CORRUPT} describing the shape of what
     *         was wrong; never null and never {@code IO_ERROR}, which is a
     *         property of the store rather than of a value it handed over
     */
    public static AuthKeyLoad decode(String value, int dcId,
                                     boolean testEnvironment)
    {
        if (value == null) { return AuthKeyLoad.notFound(); }

        int provenance = AuthKey.SEEDING_UNKNOWN_LEGACY;
        String hex = value;
        if (value.length() > 0 && value.charAt(0) == VERSION_TAG)
        {
            int end = versionEnd(value);
            if (end < 0)
            {
                return AuthKeyLoad.corrupt("malformed seeding version prefix");
            }
            provenance = parseVersion(value, end);
            if (provenance < 0)
            {
                return AuthKeyLoad.corrupt("unreadable seeding version");
            }
            hex = value.substring(end + 1);
        }

        String damage = shapeIfUnusable(hex);
        if (damage != null) { return AuthKeyLoad.corrupt(damage); }

        byte[] raw = null;
        try
        {
            raw = Hex.decode(hex);
            // The dc and environment come from the entry the value was filed
            // under: a key is only valid for the pair it was negotiated with.
            return AuthKeyLoad.found(
                    new AuthKey(raw, dcId, testEnvironment, provenance));
        }
        catch (RuntimeException e)
        {
            // AuthKey owns raw once it is constructed; reaching here means it
            // never was, so these bytes are ours to wipe.
            wipe(raw);
            return AuthKeyLoad.corrupt(className(e));
        }
    }

    /**
     * The seeding version of a stored value, without decoding the key.
     *
     * The start screen asks this on every launch and has no use for the bytes.
     * Reading only the prefix keeps 256 bytes of session out of the heap for a
     * question about one small integer.
     *
     * @return the version, or {@link AuthKey#SEEDING_NONE} when there is no
     *         usable value to read one from
     */
    public static int seedingOf(String value)
    {
        if (value == null || value.length() == 0)
        {
            return AuthKey.SEEDING_NONE;
        }
        if (value.charAt(0) != VERSION_TAG)
        {
            // Answers for a damaged value the same way it answers for a missing
            // one. A version read off something decode() would reject would put
            // a claim about seeding on a record that is not a key.
            return shapeIfUnusable(value) == null
                    ? AuthKey.SEEDING_UNKNOWN_LEGACY : AuthKey.SEEDING_NONE;
        }
        int end = versionEnd(value);
        if (end < 0) { return AuthKey.SEEDING_NONE; }
        int version = parseVersion(value, end);
        if (version < 0 || shapeIfUnusable(value.substring(end + 1)) != null)
        {
            return AuthKey.SEEDING_NONE;
        }
        return version;
    }

    // ------------------------------------------------------------- internals

    /** Index of the separator, or -1 when there is no plausible one. */
    private static int versionEnd(String value)
    {
        int limit = Math.min(value.length(), 1 + MAX_VERSION_DIGITS + 1);
        for (int i = 1; i < limit; i++)
        {
            if (value.charAt(i) == VERSION_END)
            {
                return i == 1 ? -1 : i;      // "p:" carries no digits
            }
        }
        return -1;
    }

    /** @return the version in {@code [1, end)}, or -1 when it is not digits */
    private static int parseVersion(String value, int end)
    {
        int version = 0;
        for (int i = 1; i < end; i++)
        {
            char c = value.charAt(i);
            if (c < '0' || c > '9') { return -1; }
            version = version * 10 + (c - '0');
        }
        return version;
    }

    /**
     * Validate the stored form before decoding it.
     *
     * A short value points at a per-record cap or a partial flush, a stray
     * character at the wrong encoding on the way in. Checking here rather than
     * letting {@link Hex#decode} throw keeps the description precise and keeps
     * the value out of the exception text.
     *
     * @return null when the value can be decoded, else its shape
     */
    private static String shapeIfUnusable(String hex)
    {
        if (hex.length() != HEX_LENGTH)
        {
            return "length " + hex.length() + " (expected " + HEX_LENGTH + ")";
        }
        for (int i = 0; i < hex.length(); i++)
        {
            char c = hex.charAt(i);
            boolean hexDigit = (c >= '0' && c <= '9')
                    || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F');
            // The offset, never the character: this string is the session.
            if (!hexDigit) { return "not hex at offset " + i; }
        }
        return null;
    }

    /**
     * Class name only.
     *
     * {@code tg.diag.Diag} has the same helper, but {@code tg.mt} does not
     * depend on it anywhere else and a value codec should not be the thing that
     * introduces the dependency.
     */
    private static String className(Throwable t)
    {
        String name = t.getClass().getName();
        int dot = name.lastIndexOf('.');
        return dot < 0 ? name : name.substring(dot + 1);
    }

    /** Best effort - see the note in Aes.wipe about what CLDC can promise. */
    private static void wipe(byte[] raw)
    {
        if (raw == null) { return; }
        for (int i = 0; i < raw.length; i++) { raw[i] = 0; }
    }
}
