package tg.ui;

import javax.microedition.lcdui.Canvas;
import javax.microedition.lcdui.Font;
import javax.microedition.lcdui.Graphics;

import tg.crypto.Entropy;
import tg.io.Hex;
import tg.plat.EntropyProbe;
import tg.plat.KeyTimingProbe;

/**
 * Collects key-press timings so their entropy can be measured.
 *
 * Companion to {@link KeyScreen}, which reports what the keys <i>are</i>; this
 * one reports how unpredictable <i>when</i> they arrive is. Analysis lives in
 * {@link KeyTimingProbe} so the arithmetic can be tested on the desktop against
 * synthetic timings; this class only gathers.
 *
 * <h3>Only keyPressed counts</h3>
 * {@code keyRepeated} is generated by the runtime's auto-repeat timer and
 * {@code keyReleased} follows a press by whatever the key's travel dictates.
 * Neither is timed by the user, so folding either in would manufacture entropy
 * that is not there. The whole point of the exercise is to find out whether the
 * real number is large enough to build on, which means refusing to inflate it.
 *
 * <h3>The one call site of fromUserInput</h3>
 * Every press is folded through {@code Entropy.fromUserInput}, which until now
 * had no callers anywhere in the tree despite being the method its own class
 * documentation calls the best source available. The running digest shown on
 * screen is proof the path actually executes on this handset.
 */
public class KeyTimingScreen extends Canvas
{
    /** Presses to aim for; enough for a usable MCV estimate at 1 ms resolution. */
    public static final int DEFAULT_TARGET = 50;

    private final int target;
    private final long[] times;
    private final int[] codes;
    private int count;

    /** Running fold of every press, so the screen can show the path works. */
    private byte[] digest = new byte[32];

    private final Font font;
    private final int lineHeight;
    private final Metrics metrics = new Metrics();
    private Theme theme;

    public KeyTimingScreen()
    {
        this(DEFAULT_TARGET, Theme.byId(Theme.LIGHT));
    }

    public KeyTimingScreen(int target)
    {
        this(target, Theme.byId(Theme.LIGHT));
    }

    public KeyTimingScreen(int target, Theme theme)
    {
        this.target = target < 2 ? 2 : target;
        this.times = new long[this.target];
        this.codes = new int[this.target];
        this.font = Font.getFont(Font.FACE_MONOSPACE, Font.STYLE_PLAIN, Font.SIZE_SMALL);
        this.lineHeight = Math.max(font.getHeight(), EmojiText.GLYPH);
        this.theme = theme == null ? Theme.byId(Theme.LIGHT) : theme;
    }

    public int collected()
    {
        return count;
    }

    public boolean isComplete()
    {
        return count >= target;
    }

    public void reset()
    {
        count = 0;
        digest = new byte[32];
        repaint();
    }

    /**
     * The report. Works at any count - a tester who presses twelve keys and
     * walks away still gets a reading, clearly labelled as unreliable, rather
     * than a screen that waits forever.
     */
    public String[] snapshot()
    {
        return KeyTimingProbe.analyse(times, codes, count,
                EntropyProbe.measuredTickMillis());
    }

    protected void paint(Graphics g)
    {
        metrics.update(getWidth(), getHeight(), font, font);
        UiChrome.background(g, theme, metrics);
        g.setFont(font);
        UiChrome.header(g, theme, metrics, font, "Key timing",
                count + "/" + target);

        g.setColor(theme.text);
        int y = metrics.bodyTop;

        y = line(g, y, count >= target
                ? "done - press Report"
                : "press keys at a natural pace");
        y = line(g, y, "varied keys, not one repeated");
        y += lineHeight / 2;

        y = line(g, y, "presses " + count + "/" + target);
        y = line(g, y, "last deltas (ms):");
        y = line(g, y, "  " + recentDeltas(4));
        y += lineHeight / 2;
        y = line(g, y, "digest " + Hex.encode(digest, 0, 4));

        if (count >= 2)
        {
            line(g, y, "keyRepeated is not counted");
        }
    }

    /**
     * Auto-repeat is deliberately not recorded - see the class note. It is
     * overridden rather than left to the default so that a handset which does
     * generate repeats cannot quietly route them into {@link #keyPressed}.
     */
    protected void keyRepeated(int keyCode)
    {
        // intentionally empty
    }

    protected void keyPressed(int keyCode)
    {
        long now = System.currentTimeMillis();

        if (count < target)
        {
            times[count] = now;
            codes[count] = keyCode;
            count++;
        }

        // Fold through the production path, not a copy of it. This is the only
        // place in the tree that calls it.
        try
        {
            byte[] contribution = Entropy.fromUserInput(keyCode, now);
            for (int i = 0; i < digest.length && i < contribution.length; i++)
            {
                digest[i] ^= contribution[i];
            }
        }
        catch (Throwable ignored) { /* a report screen must not die mid-run */ }

        repaint();
    }

    private String recentDeltas(int want)
    {
        if (count < 2) { return "-"; }
        StringBuffer sb = new StringBuffer(24);
        int from = count - 1 - want;
        if (from < 1) { from = 1; }
        for (int i = from; i < count; i++)
        {
            if (i > from) { sb.append(' '); }
            sb.append(times[i] - times[i - 1]);
        }
        return sb.toString();
    }

    private int line(Graphics g, int y, String s)
    {
        if (y <= metrics.bodyBottom - lineHeight)
        {
            g.drawString(s, metrics.padding, y, Graphics.TOP | Graphics.LEFT);
        }
        return y + lineHeight;
    }
}
